### ISSUE TITLE
v8.3.0 compiles against ImageMagick but not GraphicsMagick

### ISSUE THREAD

**Issue by lovell** [jcupitt/libvips#423]
As originally reported at https://github.com/lovell/sharp/issues/410#issuecomment-210191365 and confirmed locally.

```sh
$ brew install homebrew/science/vips --with-graphicsmagick
==> Installing vips from homebrew/science
==> Downloading http://www.vips.ecs.soton.ac.uk/supported/8.3/vips-8.3.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/vips-8.3.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/vips/8.3.0 --with-magick --with-magickpackage=GraphicsMagick
==> make install
Last 15 lines from /Library/Logs/Homebrew/vips/02.make:
                ~~~~~~~~~~~~~~~~  ^
magick2vips.c:229:21: error: no member named 'scenes' in 'struct _ImageInfo'
                read->image_info->scenes = strdup( page );
                ~~~~~~~~~~~~~~~~  ^
3 errors generated.
make[2]: *** [magick2vips.lo] Error 1
```

```sh
$ brew info graphicsmagick
graphicsmagick: stable 1.3.23 (bottled), HEAD
```

**Comment by lovell** [comment]
I've tried this with GraphicsMagick v1.3.23 on Linux and the same problem occurs:
```sh
magick2vips.c: In function 'read_new':
magick2vips.c:226:19: error: 'ImageInfo' has no member named 'scene'
magick2vips.c:227:19: error: 'ImageInfo' has no member named 'number_scenes'
magick2vips.c:229:19: error: 'ImageInfo' has no member named 'scenes'
make[3]: *** [magick2vips.lo] Error 1
```
I guess the `scene` logic introduced in 8e667fb is ImageMagick only.

**Comment by jcupitt** [comment]
Oh dear, yes, I struggled with pulling out a page with Wand. I'll ask on the GM lists about the best way to implement this.

**Comment by jcupitt** [comment]
I think this is fixed, or at least it works for me now with both IM and GM. I've added a configure test to pick either the IM or GM method for page access. 

GM mailing list thread for reference:

https://sourceforge.net/p/graphicsmagick/mailman/message/35019901/

**Comment by felixbuenemann** [comment]
I've backported the fix in Homebrew/hombrew-science#3569 to smooth things over until 8.3.1 is ready.

**Comment by jcupitt** [comment]
Thanks @felixbuenemann! I'll close.
