### ISSUE TITLE
Configure check for giflib4 broken

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#435]
The configure check for giflib4 was broken in commit d11a7960b7595636f59b1c802c5dca3f735a7410  while adding giflib5 support (see #407).

Both giflib 4.x and 5.x have `EGifSetGifVersion` but with different signatures:

```c
// giflib4
void EGifSetGifVersion(const char *Version);
// giflib5
void EGifSetGifVersion(GifFileType *GifFile, const bool gif89);
```

The configure check tries to compile `EGifSetGifVersion(0,0)` which fails for giflib4 (tested with 4.2.3):

```
conftest.c:121:21: error: too many arguments to function call, expected single argument 'Version', have 2 arguments
EGifSetGifVersion(0,0)
~~~~~~~~~~~~~~~~~   ^
/usr/local/include/gif_lib.h:118:1: note: 'EGifSetGifVersion' declared here
void EGifSetGifVersion(const char *Version);
^
1 error generated.
```

**Comment by jcupitt** [comment]
Oh drat, I did test this, but I didn't test the link search code. Thank you for spotting this!

Rather than testing the version, how about linking against `DGifSlurp`? This exists on giflib4 and giflib5. I added a line note.

**Comment by felixbuenemann** [comment]
Your solution is fine. Thanks, John!
