### ISSUE TITLE
Issues building with Python 3.4.3 on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by ChaoyuanYeh** [jcupitt/libvips#338]
While I was trying to build libvips, I've encountered some issues. I downloaded the .zip from the main github page. I installed all dependencies and tried `./configure`, which gave me 
    
    bash: ./configure: No such file or directory 

Then I tried `autoconf`, it gave me:

    configure.ac:13: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
    configure.ac:151: error: possibly undefined macro: AM_CONDITIONAL
    configure.ac:189: error: possibly undefined macro: AC_DEFINE
    configure.ac:256: error: possibly undefined macro: AM_WITH_DMALLOC
    configure.ac:297: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
    configure.ac:317: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
    configure.ac:327: error: possibly undefined macro: AC_PROG_LIBTOOL
    configure.ac:390: error: possibly undefined macro: AC_MSG_WARN
    configure.ac:547: error: possibly undefined macro: AC_MSG_NOTICE
    configure.ac:633: error: possibly undefined macro: AM_PATH_PYTHON
    configure.ac:758: error: possibly undefined macro: AM_CHECK_PYTHON_HEADERS

Then I tried `autoreconf -i`, I've got these errors:

    aclocal: warning: couldn't open directory 'm4': No such file or directory

When I do `./configure` again, I had this error:

    config.status: error: cannot find input file: `po/Makefile.in.in'
    
I'm wondering how I can solve these problems?

**Comment by jcupitt** [comment]
Hi, you've downloaded from git, you'll need to rebuild the configure system. There are instructions in the README.

If you download a tarball from the main vips site, it'll have the configure system made and ready to go:

http://www.vips.ecs.soton.ac.uk/supported/current/

it's quite a bit easier.

**Comment by ChaoyuanYeh** [comment]
Thanks for the response ! I was able to proceed to install. But still I wasn't able to use it in Python. 

I checked the install history, it says
 
    Libraries have been installed in:
       /usr/local/lib/python2.7/site-packages/vipsCC

and 

     /usr/bin/install -c -m 644 Vips.py '/usr/local/lib/python2.7/site-packages/gi/overrides'

There doesn't seem to be any entry related to Python3. Even in Python2.7.6, when I tried 

    from gi.repository import Vips

I got 

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name Vips

I mostly will use it in Python 3. Could you advise me on how to solve this issue? Thanks !

**Comment by jcupitt** [comment]
The installer copies `Vips.py` to the prefix overrides area for your default Python. Unfortunately your system Python won't look there, you have to copy to `/usr` yourself.

Try something like:

```
sudo cp Vips.py /usr/lib/python2.7/dist-packages/gi/overrides
sudo cp Vips.py /usr/lib/python3/dist-packages/gi/overrides
```

There are some notes about this in the docs:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-python.html

See the section that explains how `import Vips` works.

**Comment by ChaoyuanYeh** [comment]
Thanks. I eventually got it to work. Initially I could only get it to work on the Ubuntu system python ( 3.4.0).

After adding a symbolic link to Python3.4

   ln -s /usr/lib/python3/dist-packages/gi /usr/local/lib/python3.4/site-packages/

and installing `python3-gi-dbg`, I'm able to use it in Python 3.4.3 as well.

Thanks again !!

**Comment by ChaoyuanYeh** [comment]
Thanks. I got it to work in system python (3.4.0). I'm developing program, however, in a locally installed Python 3.4.3. 

I know `python3-gi` can not be installed through `pip`, so I did this: 

    sudo apt-get install python3-gi
    sudo ln -s /usr/lib/python3/dist-packages/gi /usr/local/lib/python3.4/site-packages/

But when I try to import gi using /usr/local/bin/python3 ( the Python3.4.3 I installed), I got this error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3/dist-packages/gi/__init__.py", line 36, in <module>
        from .gi import _gobject
    ImportError : No module named gi._gi

I also tried this, but ended up with the same error message

    sudo cp -r /usr/lib/python3/dist-packages/gi /usr/local/lib/python3.4/site-packages/

When I tried to do this using virtualenv, it also gave me the same error. I'm wondering how I can solve this problem?
