### PR TITLE
cplusplus - move assignment operators outside class, enables DLL exporting

### PR DESCRIPTION
**Pull request by lovell**
Hi John, this PR updates the assignment operator overloads introduced in 28efdf1 to work with MSVC by moving them "outside" the class and therefore enable DLL exporting.

Without this, MSVC generates the following rather cryptic error:
```
error C2487: '+=': member of dll interface class may not be declared with dll interface
```

There's also a bit of an MSVC annoyance in that when returning by reference, the __declspec bit has to go before the type, so what I ended up doing was ensuring a consistent modifier order across all exported functions, which looks a bit neater.

### CODE REVIEW

**Comment by jcupitt** [comment]
I don't understand why they have to be outside the class, you'd think being `friend' would be enough. I find C++ very mysterious :( 

Anyway, it looks good. Do you think this is too large a change for a minor release? I'm inclined to put it in 8.4.3 rather than waiting for 8.5 since it seems to be important for sharp.

**Comment by lovell** [comment]
Thanks for merging John.

sharp is happily using patched [VImage8.h](https://github.com/lovell/sharp/blob/quill/packaging/build/win.sh#L17) and [VImage.cpp](https://github.com/lovell/sharp/blob/quill/src/libvips/cplusplus/VImage.cpp#L773) files so this can wait for libvips 8.5.

A possible alternative to selecting individual functions for export might be to export the whole VImage class itself. This would include private functions, which feels a little dangerous and could lead to accidental coupling between lipvips-cpp.dll and anything depending upon it.

**Comment by jcupitt** [comment]
OK, 8.5 then. Good news about sharp working with 8.4 now.
